train_dataset: image-folder-custom
train_dataset_args:
    root_path: /content/drive/MyDrive/Do_an_Data/tlu-states/images
    split_file: /content/drive/MyDrive/Do_an_Data/split.json
    split: train
    augment: True

val_dataset: image-folder-custom
val_dataset_args:
    root_path: /content/drive/MyDrive/Do_an_Data/tlu-states/images
    split_file: /content/drive/MyDrive/Do_an_Data/split.json
    split: val

# Using standard ConvNet4 used in papers for miniImageNet
model: classifier
model_args:
    encoder: convnet4
    encoder_args: {}
    classifier: linear-classifier
    classifier_args: {n_classes: 15} # 15 base classes

batch_size: 64
max_epoch: 100
optimizer: sgd
optimizer_args: {lr: 0.1, weight_decay: 5.e-4, milestones: [60, 80]}

save_epoch: 10
visualize_datasets: False
